version: "3.7"
services:
  client:
    container_name: ovc-panel-client
    build: ./client
    restart: "unless-stopped"
    ports:
      - "80:8000"
  api:
    container_name: ovc-panel-api
    build: ./api
    restart: "unless-stopped"
    environment:
      MYSQL_PORT: 8002
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8001:8001"
  db:
    container_name: ovc-mariadb
    image: mariadb
    restart: "unless-stopped"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8002:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql

volumes:
  mariadb-volume:
