version: "3.7"
services:
  client:
    container_name: client-container
    build:
      context: ./client/
      dockerfile: dockerfile
    ports:
      - "80:8000"
  api:
    container_name: ovc-api
    build:
      context: ./api/
      dockerfile: dockerfile
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8001:8001"
  db:
    image: mariadb
    container_name: ovc-mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8002:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql

volumes:
  mariadb-volume:
